// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: api/types/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// These are valid condition statuses.
type ConditionStatus int32

const (
	// This is only a meaningless placeholder, to avoid zero not return.
	ConditionStatus_CONDITION_STATUS_UNSPECIFIED ConditionStatus = 0
	// True means a resource is in the condition.
	ConditionStatus_True ConditionStatus = 1
	// False means a resource is not in the condition.
	ConditionStatus_False ConditionStatus = 2
	// Unknown means kubernetes can't decide if a resource is in the condition or
	// not.
	ConditionStatus_Unknown ConditionStatus = 3
)

// Enum value maps for ConditionStatus.
var (
	ConditionStatus_name = map[int32]string{
		0: "CONDITION_STATUS_UNSPECIFIED",
		1: "True",
		2: "False",
		3: "Unknown",
	}
	ConditionStatus_value = map[string]int32{
		"CONDITION_STATUS_UNSPECIFIED": 0,
		"True":                         1,
		"False":                        2,
		"Unknown":                      3,
	}
)

func (x ConditionStatus) Enum() *ConditionStatus {
	p := new(ConditionStatus)
	*p = x
	return p
}

func (x ConditionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConditionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_types_types_proto_enumTypes[0].Descriptor()
}

func (ConditionStatus) Type() protoreflect.EnumType {
	return &file_api_types_types_proto_enumTypes[0]
}

func (x ConditionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConditionStatus.Descriptor instead.
func (ConditionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_types_types_proto_rawDescGZIP(), []int{0}
}

var File_api_types_types_proto protoreflect.FileDescriptor

var file_api_types_types_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x6b, 0x61, 0x6e, 0x74, 0x61, 0x6c, 0x6f,
	0x75, 0x70, 0x65, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x61, 0x2e, 0x61, 0x69, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2a, 0x55, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x1c, 0x43,
	0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x54, 0x72, 0x75, 0x65, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x61, 0x6c, 0x73, 0x65,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x03, 0x42,
	0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x61, 0x2d, 0x61, 0x69, 0x2f, 0x6b, 0x61, 0x6e, 0x74, 0x61, 0x6c, 0x6f,
	0x75, 0x70, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_types_types_proto_rawDescOnce sync.Once
	file_api_types_types_proto_rawDescData = file_api_types_types_proto_rawDesc
)

func file_api_types_types_proto_rawDescGZIP() []byte {
	file_api_types_types_proto_rawDescOnce.Do(func() {
		file_api_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_types_types_proto_rawDescData)
	})
	return file_api_types_types_proto_rawDescData
}

var file_api_types_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_types_types_proto_goTypes = []interface{}{
	(ConditionStatus)(0), // 0: kantaloupe.dynamia.ai.api.types.ConditionStatus
}
var file_api_types_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_types_types_proto_init() }
func file_api_types_types_proto_init() {
	if File_api_types_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_types_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_types_types_proto_goTypes,
		DependencyIndexes: file_api_types_types_proto_depIdxs,
		EnumInfos:         file_api_types_types_proto_enumTypes,
	}.Build()
	File_api_types_types_proto = out.File
	file_api_types_types_proto_rawDesc = nil
	file_api_types_types_proto_goTypes = nil
	file_api_types_types_proto_depIdxs = nil
}
