{{- if .Values.monitoring.vendorServiceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: npu-exporter
    release: {{ ternary "prometheus" "should-not-exists" ( .Values.monitoring.vendorServiceMonitor.enableAscendServicemonitor ) }}
  name: npu-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    relabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_endpoint_node_name
      targetLabel: node
    metricRelabelings:
    - action: replace
      regex: ^(.+)-[a-z0-9]{9,}-[a-z0-9]+$
      replacement: $1
      sourceLabels:
      - pod_name
      targetLabel: deployment_name
    - action: replace
      separator: /
      sourceLabels:
      - exported_namespace
      - deployment_name
      targetLabel: deployment
    - targetLabel: cluster
      replacement: local-cluster
    path: /metrics
    port: npu-metrics
  jobLabel: app
  namespaceSelector:
    matchNames:
    - npu-exporter
  selector:
    matchLabels:
      app: npu-exporter
{{- end -}}