apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "common.names.fullname" . }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - kantaloupe.dynamia.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kantaloupe.dynamia.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - kantaloupe.dynamia.io
  resources:
  - kantaloupe/status
  verbs:
  - get
  - patch
  - update
