apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kantaloupe
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: kantaloupe
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    port: 80
    protocol: HTTP