{{- if .Values.enableGateway }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kantaloupe-prometheus
  namespace: monitoring
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: kantaloupe
    namespace: kantaloupe-system 
    sectionName: prometheus
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: prometheus-kube-prometheus-prometheus
      port: 9090
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end -}}