{{- if .Values.enableGateway }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "kantaloupe.ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: kantaloupe
    namespace: {{ .Release.Namespace }}
    sectionName: http
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ include "kantaloupe.ui.fullname" . }}
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end -}}