name: Test PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**

env:
  GO_VERSION: "1.24.0"
  GOLANGCI_VERSION: 'v1.64.5'

jobs:
  get_ref:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.result.outputs.ref }}
    steps:
      - name: Get Ref
        id: result
        run: |
          echo ref=${{ github.event.pull_request.head.sha }} >> $GITHUB_OUTPUT

  static-check:
    needs: get_ref
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ needs.get_ref.outputs.ref }}
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format
      - name: Install protoc-gen-go
        run: |
          go install -mod=mod \
            github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
            github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
            google.golang.org/protobuf/cmd/protoc-gen-go \
            google.golang.org/grpc/cmd/protoc-gen-go-grpc && \
            go install -mod=mod github.com/golang/protobuf/protoc-gen-go@v1.5.4 && \
            go install -mod=mod github.com/grpc-ecosystem/protoc-gen-grpc-gateway-ts@v1.1.2
      - name: Make proto
        run: make genproto 
      - name: Run static check
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_VERSION }}
          args: "--out-${NO_FUTURE}format colored-line-number"
          skip-pkg-cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
  unit-test:
    needs: [ static-check,get_ref ]
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ needs.get_ref.outputs.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format
      - name: Install protoc-gen-go
        run: |
            go install -mod=mod \
              github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
              github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
              google.golang.org/protobuf/cmd/protoc-gen-go \
              google.golang.org/grpc/cmd/protoc-gen-go-grpc && \
              go install -mod=mod github.com/golang/protobuf/protoc-gen-go@v1.5.4 && \
              go install -mod=mod github.com/grpc-ecosystem/protoc-gen-grpc-gateway-ts@v1.1.2
      - name: Make proto
        run: make genproto 
      - name: Run unit tests
        run: make test
